/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import dao.ComunaDAO;
import dao.DatosContactoDAO;
import dao.DireccionDAO;
import dao.DiscapacidadDAO;
import dao.EmpresaDAO;
import dao.LocalidadDAO;
import dao.NacimientoDAO;
import dao.PersonaDAO;
import dao.ProvinciaDAO;
import dao.RegionDAO;
import dao.UsoInternoDAO;
import entidades.Comuna;
import entidades.DatosContacto;
import entidades.Direccion;
import entidades.Discapacidad;
import entidades.Empresa;
import entidades.Localidad;
import entidades.Nacimiento;
import entidades.Persona;
import entidades.Provincia;
import entidades.Region;
import entidades.UsoInterno;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cactus
 */
public class FormularioConsultarDatos extends javax.swing.JFrame {

    /**
     * Creates new form FormularioConsultarDatos
     */
    public FormularioConsultarDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosPersona = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarPorId = new javax.swing.JTextField();
        btnBuscarPorId = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatosDiscapacidad = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDatosContacto = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDatosUsoInterno = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDatosNacimiento = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDatosDireccion = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblDatosEmpresa = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblDireccionEmp = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tblDatosPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "RUT", "Nombres", "Apellido Paterno", "Apellido Materno", "Concurso", "Horario video", "Nivel educacional", "Etnia indigena", "Jefe de hogar", "Personas dependiente", "Estado civil"
            }
        ));
        jScrollPane1.setViewportView(tblDatosPersona);

        jLabel1.setText("Buscar por ID:");

        txtBuscarPorId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarPorIdKeyTyped(evt);
            }
        });

        btnBuscarPorId.setText("Buscar");
        btnBuscarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("DATOS PERSONA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarPorId))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tblDatosDiscapacidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Situacion discapacidad", "¿Posee credencial?"
            }
        ));
        jScrollPane2.setViewportView(tblDatosDiscapacidad);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDatosContacto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Email", "Email alternativo", "Celular", "Telefono"
            }
        ));
        jScrollPane3.setViewportView(tblDatosContacto);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblDatosUsoInterno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Correo uso interno", "Clave uso interno", "Usuario sercotec", "Clave sercotec"
            }
        ));
        jScrollPane4.setViewportView(tblDatosUsoInterno);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblDatosNacimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lugar de nacimiento", "Fecha nacimiento", "Genero"
            }
        ));
        jScrollPane5.setViewportView(tblDatosNacimiento);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblDatosDireccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Direccion", "Localidad", "Comuna", "Provincia", "Region"
            }
        ));
        jScrollPane6.setViewportView(tblDatosDireccion);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("DATOS EMPRESA");

        tblDatosEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo persona", "Numero trabajadores con contrato", "Nivel ventas anual", "Rut empresa", "Nombre empresa"
            }
        ));
        jScrollPane7.setViewportView(tblDatosEmpresa);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDireccionEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Direccion", "Localidad", "Comuna", "Provincia", "Region"
            }
        ));
        jScrollPane8.setViewportView(tblDireccionEmp);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("SIGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarPorIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorIdKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");

        }
    }//GEN-LAST:event_txtBuscarPorIdKeyTyped

    private void btnBuscarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorIdActionPerformed
        try {
            // TODO add your handling code here:
            this.listarPorId();

        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }


    }//GEN-LAST:event_btnBuscarPorIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        FormularioConsultarDatosDos abrir = new FormularioConsultarDatosDos();
        abrir.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listarPorId() throws SQLException {

        if (txtBuscarPorId.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Debe ingresar un ID", "ERROR", JOptionPane.WARNING_MESSAGE);

        }

        PersonaDAO pDAO = new PersonaDAO();
        DiscapacidadDAO dDAO = new DiscapacidadDAO();
        DatosContactoDAO dcDAO = new DatosContactoDAO();
        UsoInternoDAO uiDAO = new UsoInternoDAO();
        NacimientoDAO nDAO = new NacimientoDAO();
        DireccionDAO dirDAO = new DireccionDAO();
        LocalidadDAO locDAO = new LocalidadDAO();
        ComunaDAO comDAO = new ComunaDAO();
        ProvinciaDAO provDAO = new ProvinciaDAO();
        RegionDAO regDAO = new RegionDAO();
        EmpresaDAO empDAO = new EmpresaDAO();

        Persona p = new Persona();
        Discapacidad d = new Discapacidad();
        DatosContacto dc = new DatosContacto();
        UsoInterno ui = new UsoInterno();
        Nacimiento n = new Nacimiento();
        Direccion dir = new Direccion();
        Localidad loc = new Localidad();
        Comuna com = new Comuna();
        Provincia prov = new Provincia();
        Region reg = new Region();
        Empresa emp = new Empresa();

        pDAO.consultaForaneas(Integer.parseInt(txtBuscarPorId.getText()), d, dc, ui, n, dir);

        p.setIdPersona(Integer.parseInt(txtBuscarPorId.getText()));

        try {

            ArrayList<Persona> personas = null;
            ArrayList<Discapacidad> discapacida = null;
            ArrayList<DatosContacto> datosContact = null;
            ArrayList<UsoInterno> usoIntern = null;
            ArrayList<Nacimiento> naci = null;
            ArrayList<Direccion> direcc = null;
            ArrayList<Localidad> local = null;
            ArrayList<Comuna> comun = null;
            ArrayList<Provincia> provin = null;
            ArrayList<Region> regio = null;
            ArrayList<Empresa> empre = null;
            ArrayList<Direccion> direcEmp = null;
            ArrayList<Localidad> locaEmp = null;
            ArrayList<Comuna> comEmp = null;
            ArrayList<Provincia> provEmp = null;
            ArrayList<Region> regEmp = null;

            personas = pDAO.listarPersonaPorId(Integer.parseInt(txtBuscarPorId.getText()));
            discapacida = dDAO.listarDiscapacidadPorId(d);
            datosContact = dcDAO.listarDatosContactoPorId(dc);
            usoIntern = uiDAO.listarUsoInternoPorId(ui);
            naci = nDAO.listarNacimientoPorId(n);
            direcc = dirDAO.listarDireccionPorId(dir, loc);
            local = locDAO.listarLocalidadPorId(loc, com);
            comun = comDAO.listarComunaPorId(prov, com);
            provin = provDAO.listarProvinciaPorId(prov, reg);
            regio = regDAO.listarRegionPorId(reg);
            empre = empDAO.listarEmpresaPorId(emp, p, dir);
            direcEmp = dirDAO.listarDireccionEmpresaPorId(dir, loc);
            locaEmp = locDAO.listarLocalidadEmpresaPorId(loc, com);
            comEmp = comDAO.listarComunaEmpresaPorId(prov, com);
            provEmp = provDAO.listarProvinciaEmpresaPorId(prov, reg);
            regEmp = regDAO.listarRegionEmpresaPorId(reg);

            if (personas.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la persona con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            /*if (discapacida.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la discapacidad con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (datosContact.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontraron los datos contacto con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (usoIntern.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro datos de uso interno con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (naci.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro el nacimiento con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (direcc.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la direccion con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (local.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la localidad con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (comun.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la comuna con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (provin.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la provincia con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (regio.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la region con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (empre.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la empresa con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (direcEmp.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la direccion de empresa con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (locaEmp.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la localidad de empresa con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (comEmp.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la comuna de empresa con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (provEmp.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la provincia de empresa con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }
            if (regEmp.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la region de empresa con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }*/

            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("RUT");
            modelo.addColumn("Nombres");
            modelo.addColumn("Apellido Paterno");
            modelo.addColumn("Apellido Materno");
            modelo.addColumn("Concurso");
            modelo.addColumn("Horario video");
            modelo.addColumn("Nivel educacional");
            modelo.addColumn("Etnia indigena");
            modelo.addColumn("Jefe de hogar");
            modelo.addColumn("Personas dependiente");
            modelo.addColumn("Estado civil");

            DefaultTableModel modeloDisc = new DefaultTableModel();

            modeloDisc.addColumn("Situacion discapacidad");
            modeloDisc.addColumn("¿Posee credencial?");

            DefaultTableModel modeloDatosContacto = new DefaultTableModel();

            modeloDatosContacto.addColumn("Email");
            modeloDatosContacto.addColumn("Email alternativo");
            modeloDatosContacto.addColumn("Celular");
            modeloDatosContacto.addColumn("Telefono");

            DefaultTableModel modeloUsoInterno = new DefaultTableModel();

            modeloUsoInterno.addColumn("Correo uso interno");
            modeloUsoInterno.addColumn("Clave uso interno");
            modeloUsoInterno.addColumn("Usuario sercotec");
            modeloUsoInterno.addColumn("Clave sercotec");

            DefaultTableModel modeloNacimiento = new DefaultTableModel();

            modeloNacimiento.addColumn("Lugar de nacimiento");
            modeloNacimiento.addColumn("Fecha nacimiento");
            modeloNacimiento.addColumn("Genero");

            DefaultTableModel modeloDireccion = new DefaultTableModel();

            modeloDireccion.addColumn("Direccion");
            modeloDireccion.addColumn("Localidad");
            modeloDireccion.addColumn("Comuna");
            modeloDireccion.addColumn("Provincia");
            modeloDireccion.addColumn("Region");

            DefaultTableModel modeloEmpresa = new DefaultTableModel();

            modeloEmpresa.addColumn("Tipo persona");
            modeloEmpresa.addColumn("Numero trabajadores con contrato");
            modeloEmpresa.addColumn("Nivel ventas anual");
            modeloEmpresa.addColumn("Rut empresa");
            modeloEmpresa.addColumn("Nombre empresa");

            DefaultTableModel modeloDireccionEmp = new DefaultTableModel();

            modeloDireccionEmp.addColumn("Direccion");
            modeloDireccionEmp.addColumn("Localidad");
            modeloDireccionEmp.addColumn("Comuna");
            modeloDireccionEmp.addColumn("Provincia");
            modeloDireccionEmp.addColumn("Region");

            for (Persona per : personas) {
                String[] fila = new String[11];
                fila[0] = Integer.toString(per.getRut());
                fila[1] = per.getNombres();
                fila[2] = per.getApellidoPaterno();
                fila[3] = per.getApellidoMaterno();
                fila[4] = per.getConcurso();
                fila[5] = per.getHorarioVideo();
                fila[6] = per.getNivelEducacional();
                fila[7] = per.getEtniaIndigena();
                fila[8] = per.getJefeHogar();
                fila[9] = Integer.toString(per.getPersonasDependiente());
                fila[10] = per.getEstadoCivil();

                modelo.addRow(fila);
            }

            tblDatosPersona.setModel(modelo);

            for (Discapacidad disc : discapacida) {

                String[] fila = new String[2];
                fila[0] = disc.getSituacionDiscapacidad();
                fila[1] = disc.getCredencialDiscapacidad();

                modeloDisc.addRow(fila);

            }

            tblDatosDiscapacidad.setModel(modeloDisc);

            for (DatosContacto datCon : datosContact) {

                String[] fila = new String[4];
                fila[0] = datCon.getEmail();
                fila[1] = datCon.getEmailAlternativo();
                fila[2] = datCon.getCelular();
                fila[3] = datCon.getTelefono();

                modeloDatosContacto.addRow(fila);

            }

            tblDatosContacto.setModel(modeloDatosContacto);

            for (UsoInterno usInt : usoIntern) {

                String[] fila = new String[4];
                fila[0] = usInt.getCorreo();
                fila[1] = usInt.getClave();
                fila[2] = usInt.getUsuarioSercotec();
                fila[3] = usInt.getClaveSercotec();

                modeloUsoInterno.addRow(fila);

            }

            tblDatosUsoInterno.setModel(modeloUsoInterno);

            for (Nacimiento nac : naci) {

                String[] fila = new String[3];
                fila[0] = nac.getLugarNacimiento();
                fila[1] = nac.getFechaNacimiento();
                fila[2] = nac.getGenero();

                modeloNacimiento.addRow(fila);

            }

            tblDatosNacimiento.setModel(modeloNacimiento);

            for (Direccion dire : direcc) {
                String[] fila = new String[5];
                fila[0] = dire.getDireccion();

                for (Localidad loca : local) {
                    fila[1] = loca.getNombreLocalidad();

                    for (Comuna comu : comun) {
                        fila[2] = comu.getNombreComuna();

                        for (Provincia provi : provin) {
                            fila[3] = provi.getNombreProvincia();

                            for (Region re : regio) {
                                fila[4] = re.getNombreRegion();

                                modeloDireccion.addRow(fila);
                            }

                        }

                    }
                }

            }

            tblDatosDireccion.setModel(modeloDireccion);

            for (Empresa empres : empre) {

                String[] fila = new String[5];
                fila[0] = empres.getTipoPersona();
                fila[1] = Integer.toString(empres.getNumeroTrabajadoresContrato());
                fila[2] = Integer.toString(empres.getNivelVentasAnual());
                fila[3] = Integer.toString(empres.getRutEmpresa());
                fila[4] = empres.getNombreEmpresa();

                modeloEmpresa.addRow(fila);

            }

            tblDatosEmpresa.setModel(modeloEmpresa);

            for (Direccion dirEmp : direcEmp) {

                String[] fila = new String[5];
                fila[0] = dirEmp.getDireccionEmp();

                for (Localidad locEmp : locaEmp) {
                    fila[1] = locEmp.getNombreLocalidadEmp();

                    for (Comuna comunEmp : comEmp) {
                        fila[2] = comunEmp.getNombreComunaEmp();

                        for(Provincia proEmp : provEmp){
                            fila[3] = proEmp.getNombreProvinciaEmp();
                            
                            for(Region regioEmp : regEmp){
                                fila[4] = regioEmp.getNombreRegionEmp();
                                
                                modeloDireccionEmp.addRow(fila);
                            }
                        }
                    }

                }

            }

            tblDireccionEmp.setModel(modeloDireccionEmp);

            /*for(Localidad loca : local){
                
                String[] fila = new String[2];
                fila[1] = loca.getNombreLocalidad();
                
                modeloDireccion.addRow(fila);
                
            }
            tblDatosDireccion.setModel(modeloDireccion);*/
        } catch (Exception e) {

            System.out.println("ERROR: " + e.getMessage());

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioConsultarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioConsultarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioConsultarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioConsultarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioConsultarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPorId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tblDatosContacto;
    private javax.swing.JTable tblDatosDireccion;
    private javax.swing.JTable tblDatosDiscapacidad;
    private javax.swing.JTable tblDatosEmpresa;
    private javax.swing.JTable tblDatosNacimiento;
    private javax.swing.JTable tblDatosPersona;
    private javax.swing.JTable tblDatosUsoInterno;
    private javax.swing.JTable tblDireccionEmp;
    private javax.swing.JTextField txtBuscarPorId;
    // End of variables declaration//GEN-END:variables
}
