/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import dao.ListaRespuestaDAO;
import dao.RespuestaDAO;
import entidades.ListaRespuesta;
import entidades.Persona;
import entidades.Respuesta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static vistas.FormularioConsultarDatosTres.txaResCanvas1;
import static vistas.FormularioConsultarDatosTres.txaResCanvas2;
import static vistas.FormularioConsultarDatosTres.txaResCanvas3;
import static vistas.FormularioConsultarDatosTres.txaResCanvas4;

/**
 *
 * @author Cactus
 */
public class FormularioConsultarDatosDos extends javax.swing.JFrame {

    /**
     * Creates new form FormularioConsultarDatosDos
     */
    public FormularioConsultarDatosDos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtNombreProyecto2 = new javax.swing.JTextField();
        lblA21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDescripcionProyecto4 = new javax.swing.JTextArea();
        lblA22 = new javax.swing.JLabel();
        lblA23 = new javax.swing.JLabel();
        lblA24 = new javax.swing.JLabel();
        lblA25 = new javax.swing.JLabel();
        lblA26 = new javax.swing.JLabel();
        lblA27 = new javax.swing.JLabel();
        lblA28 = new javax.swing.JLabel();
        lblA29 = new javax.swing.JLabel();
        lblA30 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaRubro = new javax.swing.JTextArea();
        txtAutorizacionVideoRedesSociales = new javax.swing.JTextField();
        txtAutorizacionDireccionComercial = new javax.swing.JTextField();
        txtPrincipalesClientes = new javax.swing.JTextField();
        txtFormaPaganClientes = new javax.swing.JTextField();
        txtNivelDeudaMensual = new javax.swing.JTextField();
        txtPrincipalFuenteFinanciamiento = new javax.swing.JTextField();
        txtFormaPago = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblA31 = new javax.swing.JLabel();
        lblA32 = new javax.swing.JLabel();
        lblA33 = new javax.swing.JLabel();
        lblA34 = new javax.swing.JLabel();
        lblA35 = new javax.swing.JLabel();
        lblA36 = new javax.swing.JLabel();
        lblA37 = new javax.swing.JLabel();
        lblA38 = new javax.swing.JLabel();
        lblA39 = new javax.swing.JLabel();
        txtSocioNegocio = new javax.swing.JTextField();
        txtPersonasACargo = new javax.swing.JTextField();
        txtRecursosCrecerNegocio = new javax.swing.JTextField();
        txtListaServiciosAsesoria = new javax.swing.JTextField();
        txtNotableSerEmprendedor = new javax.swing.JTextField();
        txtPrincipalVentajaProducto = new javax.swing.JTextField();
        txtPromedioHorasEfectiva = new javax.swing.JTextField();
        txtEmpresasNegociosDueno = new javax.swing.JTextField();
        txtNivelConocimiento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarPorId = new javax.swing.JTextField();
        btnBuscarPorId = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblA21.setText("Nombre del proyecto");

        txaDescripcionProyecto4.setColumns(20);
        txaDescripcionProyecto4.setRows(5);
        jScrollPane3.setViewportView(txaDescripcionProyecto4);

        lblA22.setText("Descripcion del proyecto");

        lblA23.setText("Seleccion del rubro");

        lblA24.setText("Autorizacion del video en redes sociales");

        lblA25.setText("Autorizacion uso de direccion comercial de empresa localizacion, ubicacion en plataforma en SERCOTEC ");

        lblA26.setText("Principales clientes");

        lblA27.setText("De que forma pagan a los clientes");

        lblA28.setText("Cual es la principal fuente de financiamiento con que pone en marcha su negocio?");

        lblA29.setText("Cual es la forma de pago que utiliza para pagar materia prima o insumos del negocio?");

        lblA30.setText("Nivel de deuda mensual que tiene el negocio en relacion a las ventas netas mensuales");

        txaRubro.setColumns(20);
        txaRubro.setRows(5);
        jScrollPane4.setViewportView(txaRubro);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblA22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblA21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreProyecto2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblA25)))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblA23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblA28)
                    .addComponent(lblA29)
                    .addComponent(lblA30)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblA27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFormaPaganClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblA24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAutorizacionVideoRedesSociales, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAutorizacionDireccionComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblA26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrincipalesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNivelDeudaMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrincipalFuenteFinanciamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProyecto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblA21))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblA22)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblA23)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA24)
                    .addComponent(txtAutorizacionVideoRedesSociales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblA25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAutorizacionDireccionComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA26)
                    .addComponent(txtPrincipalesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA27)
                    .addComponent(txtFormaPaganClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lblA30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNivelDeudaMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lblA28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrincipalFuenteFinanciamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblA29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        lblA31.setText("Cuenta con algun socio en su negocio (socio formal o informal).");

        lblA32.setText("Cuantas personas a cargo ha tenido en trabajos anteriores?");

        lblA33.setText("Si tienes que conseguir recursos para hacer crecer su negocio cual seria la mejor alternativa para conseguir.");

        lblA34.setText("De la siguiente lista de servicios o asesoria externa, escoja una");

        lblA35.setText("Que es lo mas notable de ser emprendedor?");

        lblA36.setText("Cual es la principal ventaja que usted identifica en productos y/o servicios por sobre su competencia?");

        lblA37.setText("De cuantas empresas o negocios es o ha sido dueño?");

        lblA38.setText("Señale nivel de conocimiento y manejo que posee en marketing comercial y generacion de redes comerciales");

        lblA39.setText("Promedio de horas efectivas de capacitacion en los ultimos 3 años");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblA33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSocioNegocio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA32, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA39)
                            .addComponent(lblA37)
                            .addComponent(lblA36)
                            .addComponent(lblA35)
                            .addComponent(lblA34)
                            .addComponent(lblA38)
                            .addComponent(txtPersonasACargo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRecursosCrecerNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtListaServiciosAsesoria, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNotableSerEmprendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrincipalVentajaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPromedioHorasEfectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmpresasNegociosDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivelConocimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblA31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSocioNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblA32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPersonasACargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblA33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRecursosCrecerNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblA34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtListaServiciosAsesoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblA35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNotableSerEmprendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblA36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrincipalVentajaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblA39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPromedioHorasEfectiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblA37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmpresasNegociosDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(lblA38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNivelConocimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        jLabel1.setText("Buscar por ID:");

        btnBuscarPorId.setText("Buscar");
        btnBuscarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorIdActionPerformed(evt);
            }
        });

        jButton1.setText("SIGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ATRAS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarPorId)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtBuscarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPorId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        FormularioConsultarDatosTres abrir = new FormularioConsultarDatosTres();
        abrir.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FormularioConsultarDatos abrir = new FormularioConsultarDatos();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBuscarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorIdActionPerformed
        // TODO add your handling code here:

        Persona p = new Persona();
        Respuesta r = new Respuesta();
        ListaRespuestaDAO lrDAO = new ListaRespuestaDAO();

        if (txtBuscarPorId.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Debe ingresar un id", "ERROR", JOptionPane.WARNING_MESSAGE);

        } else {

            p.setIdPersona(Integer.parseInt(txtBuscarPorId.getText()));

            try {

                ArrayList<String> resp = null;

                resp = lrDAO.listarRespuestaPorId(r, p);
                if (resp.size() == 0) {

                    JOptionPane.showMessageDialog(null, "No se encontraron respuestas con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

                    
                }

                txtNombreProyecto2.setText(resp.get(0));
                txaDescripcionProyecto4.setText(resp.get(1));
                txaRubro.setText(resp.get(2));
                txtAutorizacionVideoRedesSociales.setText(resp.get(3));
                txtAutorizacionDireccionComercial.setText(resp.get(4));
                txtPrincipalesClientes.setText(resp.get(5));
                txtFormaPaganClientes.setText(resp.get(6));
                txtNivelDeudaMensual.setText(resp.get(7));
                txtPrincipalFuenteFinanciamiento.setText(resp.get(8));
                txtFormaPago.setText(resp.get(9));
                txtSocioNegocio.setText(resp.get(10));
                txtPersonasACargo.setText(resp.get(11));
                txtRecursosCrecerNegocio.setText(resp.get(12));
                txtListaServiciosAsesoria.setText(resp.get(13));
                txtNotableSerEmprendedor.setText(resp.get(14));
                txtPrincipalVentajaProducto.setText(resp.get(15));
                txtPromedioHorasEfectiva.setText(resp.get(16));
                txtEmpresasNegociosDueno.setText(resp.get(17));
                txtNivelConocimiento.setText(resp.get(18));
                /*txtNombreProyecto2.setText(resp.get(19).toString());
                txtNombreProyecto2.setText(resp.get(20).toString());
                txtNombreProyecto2.setText(resp.get(21).toString());
                txtNombreProyecto2.setText(resp.get(22).toString());
                txtNombreProyecto2.setText(resp.get(23).toString());
                txtNombreProyecto2.setText(resp.get(24).toString());
                txtNombreProyecto2.setText(resp.get(25).toString());
                txtNombreProyecto2.setText(resp.get(26).toString());
                txtNombreProyecto2.setText(resp.get(27).toString());
                txtNombreProyecto2.setText(resp.get(28).toString());
                txtNombreProyecto2.setText(resp.get(29).toString());
                txtNombreProyecto2.setText(resp.get(30).toString());
                txtNombreProyecto2.setText(resp.get(31).toString());
                txtNombreProyecto2.setText(resp.get(32).toString());
                txtNombreProyecto2.setText(resp.get(33).toString());
                txtNombreProyecto2.setText(resp.get(34).toString());*/

            } catch (Exception e) {

                System.out.println("ERROR: " + e.getMessage());

            }
        }


    }//GEN-LAST:event_btnBuscarPorIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioConsultarDatosDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioConsultarDatosDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioConsultarDatosDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioConsultarDatosDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioConsultarDatosDos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPorId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblA21;
    private javax.swing.JLabel lblA22;
    private javax.swing.JLabel lblA23;
    private javax.swing.JLabel lblA24;
    private javax.swing.JLabel lblA25;
    private javax.swing.JLabel lblA26;
    private javax.swing.JLabel lblA27;
    private javax.swing.JLabel lblA28;
    private javax.swing.JLabel lblA29;
    private javax.swing.JLabel lblA30;
    private javax.swing.JLabel lblA31;
    private javax.swing.JLabel lblA32;
    private javax.swing.JLabel lblA33;
    private javax.swing.JLabel lblA34;
    private javax.swing.JLabel lblA35;
    private javax.swing.JLabel lblA36;
    private javax.swing.JLabel lblA37;
    private javax.swing.JLabel lblA38;
    private javax.swing.JLabel lblA39;
    public static javax.swing.JTextArea txaDescripcionProyecto4;
    private javax.swing.JTextArea txaRubro;
    private javax.swing.JTextField txtAutorizacionDireccionComercial;
    private javax.swing.JTextField txtAutorizacionVideoRedesSociales;
    private javax.swing.JTextField txtBuscarPorId;
    private javax.swing.JTextField txtEmpresasNegociosDueno;
    private javax.swing.JTextField txtFormaPaganClientes;
    private javax.swing.JTextField txtFormaPago;
    private javax.swing.JTextField txtListaServiciosAsesoria;
    private javax.swing.JTextField txtNivelConocimiento;
    private javax.swing.JTextField txtNivelDeudaMensual;
    public static javax.swing.JTextField txtNombreProyecto2;
    private javax.swing.JTextField txtNotableSerEmprendedor;
    private javax.swing.JTextField txtPersonasACargo;
    private javax.swing.JTextField txtPrincipalFuenteFinanciamiento;
    private javax.swing.JTextField txtPrincipalVentajaProducto;
    private javax.swing.JTextField txtPrincipalesClientes;
    private javax.swing.JTextField txtPromedioHorasEfectiva;
    private javax.swing.JTextField txtRecursosCrecerNegocio;
    private javax.swing.JTextField txtSocioNegocio;
    // End of variables declaration//GEN-END:variables
}
